# Generated by Django 4.0.3 on 2022-03-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('income', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('marital_status', models.BooleanField()),
                ('status', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField()),
                ('fuel_type', models.CharField(max_length=10)),
                ('vehicle_segment', models.CharField(max_length=5)),
                ('premium', models.FloatField()),
                ('body_injury_liability', models.BooleanField()),
                ('personal_injury_liability', models.BooleanField()),
                ('property_injury_liability', models.BooleanField()),
                ('collision_liability', models.BooleanField()),
                ('comprehensive_liability', models.BooleanField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.customer')),
            ],
        ),
    ]
