# Generated by Django 4.0.3 on 2022-03-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
